Feature
IBUNHABIBU/weather-app pull request #1
Opened 2020-08-13 15:24 UTC by IBUNHABIBU

-The weather app project is ready. We can able to fetch the temperature data from weathermap api 
and display it to the web browser.

2020-08-14 14:11 UTC, shshamim63 requested changes
## :recycle: Changes Required :recycle: 
___
Hi @IBUNHABIBU :wave: 
Awesome job, I liked the way you have added temperature data, seems eye-catching to me :clap: . But there are some tasks that you need to add to make this project complete. Let's check them.
___
### :spades: Mandatory Changes :spades: 
___
- Please update your readme a bit more. Check the comments.
- It should contain a toggle control to determine if the result will be shown in Celsius or Fahrenheit ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- It should change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
___
:rocket: Just a reminder for the upcoming tasks. Keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)
___
#### Please resolve the issues mentioned above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-08-14 14:11 UTC, shshamim63 commented on README.md
> +## link to  [Video presentation](https://#"Loom")
You do not have any video presentation. Please remove it.

2020-08-14 14:11 UTC, shshamim63 commented on README.md
> +## [Live demo](https://raw.githack.com/IBUNHABIBU/weather-app/feature/dist/index.html "Of the project") of the project
Live version is not working.

2020-08-17 18:45 UTC, IBUNHABIBU commented
I have done the following changes
- Adding the toggling switch to change the temperature from Celsius to Fahrenheit 
- Adding the feature for showing weather status icon like cloudy sunny etc.
- Adding the live link to the readme file

2020-08-17 22:26 UTC, shloch requested changes
## Hello @IBUNHABIBU , 

Great work, you brought a whole lot of modifications as proposed and it works greatly

![weather](https://user-images.githubusercontent.com/40712459/90449899-4699c480-e0e0-11ea-9872-fd6ac396fb1c.gif)

### [changes required]

- You however forgot one modification proposed, which is [changing the page look](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) based on the temperature value,
You can do this by basically changing the background image with maybe sun for a hot temperature and a cold-ice background for a cold temperature value for example

- Also, I would add that you should [separate DOM from LOGIC](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png), main logic in this project is the code to fetch data from API, please put that in a separate file and import it into `app.js`

It's a good thing, you've already got things running correctly...Please let's polish the project
Happy coding

2020-08-17 22:26 UTC, shloch commented on src/modules/app.js
> +};
logic code

2020-08-17 22:26 UTC, shloch commented on src/modules/app.js
> +}
logic code

2020-08-20 07:56 UTC, IBUNHABIBU commented
- I have seperated the application logic from dom manipulation in a separate file
- I have used icons from openweathermap to show the status of the weathe i.e cloudy with cloud icon and sunny with sun icon

2020-08-20 12:53 UTC, mosaaleb requested changes
#### Well done @IBUNHABIBU :clap:

Excellent job handling the requirements from the prevoius review. Yet there is some requirements needs to be met before moving on.

- [ ] The application should change its appearance based on the received data.

!()[https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png]

Also please check out the comments below.


Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-08-20 12:53 UTC, mosaaleb commented on src/modules/fetch.js
> +//     .then(response => response.json())
- [ ] Comments: It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history .

2020-08-20 12:53 UTC, mosaaleb commented on src/modules/app.js
> +    .then(response => response.json())
- [ ] **[OPTIONAL]** What about adding catch when there is no search results found, and displaying useful information to the user?

2020-08-23 14:21 UTC, IBUNHABIBU commented on src/modules/app.js
> +};
-I have implemented the feature for the page to change background according to the weather status

2020-08-23 17:44 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi @IBUNHABIBU :wave: 

Good job, no need for further review! :smile: 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-08-23 19:13 UTC, merged